v {xschem version=3.4.8RC file_version=1.3}
G {}
K {}
V {}
S {}
F {}
E {}
P 4 5 1580 -630 1580 -890 1980 -890 1980 -630 1580 -630 {}
T {Based on a template made by R. Timothy Edwards
November 27, 2023
Revision 0
Open sourced under Apache 2.0 license} 2000 -1720 0 0 0.4 0.4 {}
T {Servo Loop} 1650 -680 0 0 0.4 0.4 {}
N 1690 -1170 1690 -1080 {lab=vdd}
N 1690 -1000 1690 -910 {lab=vss}
N 1650 -980 1650 -950 {lab=#net1}
N 2000 -980 2180 -980 {
lab=VSUB}
N 1000 -950 1650 -950 {
lab=#net1}
N 770 -1170 1690 -1170 {
lab=vdd}
N 1220 -910 1220 -680 {
lab=vss}
N 1220 -910 1690 -910 {
lab=vss}
N 1000 -950 1000 -680 {
lab=#net1}
N 770 -1170 770 -780 {
lab=vdd}
N 770 -720 770 -620 {
lab=VSUB}
N 750 -620 770 -620 {
lab=VSUB}
N 870 -1070 890 -1070 {lab=inp}
N 1570 -1010 1600 -1010 {lab=inm}
N 770 -620 1790 -620 {
lab=VSUB}
N 890 -720 890 -680 {
lab=inp}
N 1930 -1040 2200 -1040 {
lab=out}
N 1350 -720 1350 -650 {lab=inp}
N 890 -720 1350 -720 {lab=inp}
N 890 -1070 890 -720 {
lab=inp}
N 1350 -650 1620 -650 {lab=inp}
N 1930 -780 1930 -720 {lab=#net2}
N 1830 -720 1930 -720 {lab=#net2}
N 1880 -780 1930 -780 {lab=#net2}
N 1930 -810 1930 -780 {lab=#net2}
N 1790 -780 1820 -780 {lab=#net3}
N 1930 -1040 1930 -870 {lab=out}
N 1770 -1040 1930 -1040 {
lab=out}
N 1790 -670 1790 -620 {lab=VSUB}
N 1830 -680 1830 -650 {lab=inp}
N 1620 -650 1830 -650 {lab=inp}
N 1790 -780 1790 -730 {lab=#net3}
N 1730 -780 1790 -780 {lab=#net3}
N 1620 -780 1670 -780 {lab=inm}
N 1620 -780 1620 -740 {lab=inm}
N 1620 -680 1620 -650 {lab=inp}
N 1570 -780 1620 -780 {lab=inm}
N 1570 -1010 1570 -780 {lab=inm}
N 1540 -1010 1570 -1010 {lab=inm}
N 1480 -1070 1600 -1070 {lab=#net4}
N 890 -1070 1420 -1070 {lab=inp}
C {devices/code_shown.sym} 40 -1690 0 0 {name=SETUP only_toplevel=false value="* CACE gensim simulation file CACE\{filename\}_CACE\{N\}
* Generated by CACE gensim, Efabless Corporation (c) 2023
* Find the current through the amplifier under condition of static input

.include CACE\{DUT_path\}

.lib cornerMOSlv.lib CACE\{corner\}
.lib cornerCAP.lib cap_typ

.option TEMP=CACE\{temperature\}
* Flag unsafe operating conditions (exceeds models' specified limits)
.option warn=1
"}
C {OTA1336.sym} 1680 -1040 0 0 {name=x1}
C {isource.sym} 1000 -650 0 0 {name=Ibias value="DC CACE\{Ibias\}"}
C {title-3.sym} 0 0 0 0 {name=l2 author="IHP-GmbH 2026" title="CACE input offset template " rev=1.0 lock=true}
C {devices/vsource.sym} 890 -650 0 0 {name=VVcm value="DC CACE\{Vcm\}" savecurrent=false}
C {devices/lab_pin.sym} 750 -620 0 0 {name=p1 sig_type=std_logic lab=VSUB}
C {devices/vsource.sym} 1220 -650 0 0 {name=Vvss value="DC CACE\{Vvss\}" savecurrent=false}
C {devices/lab_wire.sym} 1370 -1170 0 1 {name=p11 sig_type=std_logic lab=vdd}
C {devices/lab_wire.sym} 1370 -910 0 1 {name=p24 sig_type=std_logic lab=vss}
C {devices/lab_wire.sym} 2200 -1040 0 0 {name=p25 sig_type=std_logic lab=out}
C {devices/res.sym} 2000 -1010 0 0 {name=Rout
value=CACE\{Rout\}
device=resistor}
C {devices/capa.sym} 2140 -1010 0 0 {name=Cout
value=CACE\{Cout\}}
C {devices/lab_pin.sym} 2180 -980 0 1 {name=p27 sig_type=std_logic lab=VSUB}
C {devices/vsource.sym} 770 -750 0 0 {name=Vvdd value="DC CACE\{Vvdd\}" savecurrent=false}
C {devices/code_shown.sym} 30 -1390 0 0 {name=CONTROL only_toplevel=false value=".control
op
let voffset = (inp - inm)
echo $&voffset  > CACE\{simpath\}/CACE\{filename\}_CACE\{N\}.data
quit
.endc
"}
C {devices/res.sym} 1070 -590 0 0 {name=RSUB
value=0.01
device=resistor}
C {devices/gnd.sym} 1070 -560 0 0 {name=l1 lab=GND}
C {devices/lab_pin.sym} 870 -1070 0 0 {name=p2 sig_type=std_logic lab=inp}
C {devices/lab_pin.sym} 1540 -1010 0 0 {name=p12 sig_type=std_logic lab=inm}
C {vcvs.sym} 1790 -700 0 1 {name=E1 value=1000}
C {devices/res.sym} 1700 -780 1 0 {name=Rfb
value=99.9k
device=resistor}
C {devices/capa.sym} 1850 -780 1 0 {name=Cfb
value=5u}
C {devices/res.sym} 1620 -710 0 0 {name=Rfb1
value=100
device=resistor}
C {devices/res.sym} 1930 -840 0 0 {name=Rfb2
value=99.9k
device=resistor}
C {devices/res.sym} 1450 -1070 1 0 {name=Rfb3
value=100
device=resistor}
